name: Go Lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  golangci-lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-go@v7
        with:
          go-version: stable

      - uses: golangci/golangci-lint-action@v9
        with:
          version: v2.14.0

  govulncheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-go@v7
        with:
          go-version: stable

      - name: govulncheck
        run: go run golang.org/x/vuln/cmd/govulncheck@latest ./...
